"""
Qdrant vector database integration for semantic search and project similarity.
Stores document embeddings generated by DeepSeek R1 / nomic-embed-text.
"""

import os
from typing import Optional, List, Dict
from qdrant_client import QdrantClient
from qdrant_client.models import Distance, VectorParams, PointStruct

from app.ai.ollama_client import generate_embedding

QDRANT_HOST = os.getenv("QDRANT_HOST", "http://localhost:6333")
COLLECTION_NAME = "vigil_documents"
VECTOR_SIZE = 768  # nomic-embed-text dimension

# Lazy-init client
_qdrant: Optional[QdrantClient] = None


def get_qdrant() -> QdrantClient:
    global _qdrant
    if _qdrant is None:
        _qdrant = QdrantClient(url=QDRANT_HOST)
    return _qdrant


def init_collection() -> bool:
    """Create the collection if it doesn't exist."""
    try:
        client = get_qdrant()
        collections = client.get_collections().collections
        names = [c.name for c in collections]
        if COLLECTION_NAME not in names:
            client.create_collection(
                collection_name=COLLECTION_NAME,
                vectors_config=VectorParams(size=VECTOR_SIZE, distance=Distance.COSINE),
            )
            print(f"Created Qdrant collection: {COLLECTION_NAME}")
        return True
    except Exception as e:
        print(f"Qdrant init failed: {e}")
        return False


async def index_document(doc_id: str, text: str, metadata: Optional[Dict] = None) -> bool:
    """Generate embedding and store in Qdrant."""
    try:
        embedding = await generate_embedding(text)
        if not embedding:
            return False

        client = get_qdrant()
        init_collection()

        client.upsert(
            collection_name=COLLECTION_NAME,
            points=[
                PointStruct(
                    id=doc_id,
                    vector=embedding,
                    payload=metadata or {"text": text[:500]}
                )
            ]
        )
        return True
    except Exception as e:
        print(f"Index document failed: {e}")
        return False


async def search_similar(query_text: str, limit: int = 5) -> List[Dict]:
    """Find most similar documents to query text."""
    try:
        embedding = await generate_embedding(query_text)
        if not embedding:
            return []

        client = get_qdrant()
        init_collection()

        results = client.search(
            collection_name=COLLECTION_NAME,
            query_vector=embedding,
            limit=limit,
            with_payload=True
        )

        return [
            {
                "id": r.id,
                "score": r.score,
                "payload": r.payload
            }
            for r in results
        ]
    except Exception as e:
        print(f"Search similar failed: {e}")
        return []


def delete_document(doc_id: str) -> bool:
    """Remove a document from the vector index."""
    try:
        client = get_qdrant()
        client.delete(collection_name=COLLECTION_NAME, points_selector=[doc_id])
        return True
    except Exception as e:
        print(f"Delete document failed: {e}")
        return False
